Namespacename: myapp-2026

Deploymentname: deployment-2026

Servicename: service-2026

Ingressname: ingress-2026

labels:
  app.kubernetes.io/name: app-2026

matchLabels:
  app.kubernetes.io/name: app-2026

selector:
  app.kubernetes.io/name: app-2026

image:
  repository: 487509570044.dkr.ecr.us-east-1.amazonaws.com/demo-app-repo:latest       # <--- replace with your image repo
  tag: latest                        # <--- replace with your image tag
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 5000                   # Flask container port (change if different)
  type: ClusterIP

annotations:
  kubernetes.io/ingress.class: alb
  alb.ingress.kubernetes.io/scheme: internet-facing
  alb.ingress.kubernetes.io/target-type: instance
