{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flask-app.fullname" . }}-ingress
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "flask-app.fullname" . }}-svc
                port:
                  number: {{ .Values.service.port }}
{{- end }}
